AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation stack for creating an S3 bucket, Glue Database, Table, and Athena query capability for an S3 CSV file."

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: demo-poc-iata
      
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: "demo_poc_db"

  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "sales_records_table"
        TableType: "EXTERNAL_TABLE"
        Parameters:
          classification: "parquet"
          has_encrypted_data: "false"
        StorageDescriptor:
          Columns:
            - Name: "country"
              Type: "string"
            - Name: "item_type"
              Type: "string"
            - Name: "sales_channel"
              Type: "string"
            - Name: "order_priority"
              Type: "string"
            - Name: "order_date"
              Type: "string"
            - Name: "order_id"
              Type: "bigint"
            - Name: "units_sold"
              Type: "int"
            - Name: "unit_price"
              Type: "double"
            - Name: "unit_cost"
              Type: "double"
            - Name: "total_revenue"
              Type: "double"
            - Name: "total_cost"
              Type: "double"
            - Name: "total_profit"
              Type: "double"
          Location: "s3://demo-poc-iata/iata-workflow/parquet/2024-11-19-23-25-25/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          Compressed: false
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          StoredAsSubDirectories: false

Outputs:
  GlueDatabaseName:
    Value: !Ref GlueDatabase
    Description: "The name of the Glue Database."

  GlueTableName:
    Value: "sales_records_table"
    Description: "The name of the Glue Table."
