AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation stack for creating an S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: demo-poc-iata